server:
  port: 8080
  servlet:
    context-path: /services-apis/v1

app:
  allowedOrigins: "*"
  allowedMethods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
  allowedHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Headers,Access-Control-Allow-Methods,Accept,Authorization,Content-Type,Method,Origin,X-Forwarded-For,X-Real-IP,Idp,Intercepterrors,Interceptormensajes,Interceptorloading
  exposedHeaders: X-Get-Header

spring:
  application:
    name: services-apis

logging:
  file:
    name: ${spring.application.name}.log
  pattern:
    file: "%d %p %c{1.} [%t] %m%n"
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"

nasa-apis-path:
  images: https://images-api.nasa.gov
  pathSearch: /search